name: Kriteria 3 - CI Pipeline & Docker

on:
  push:
    branches: [ "main" ] # Trigger setiap ada push ke branch main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-train-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    # 3. Install Dependencies
    - name: Install dependencies
      run: |
        pip install mlflow pandas scikit-learn numpy matplotlib

    # 4. Run MLflow Project (Training)
    - name: Train Model
      run: |
        # TIDAK PERLU 'cd kriteria3' lagi karena file sudah di root
        python modelling.py

    # 5. Commit Artifacts (Model Output)
    - name: Commit Model Artifacts
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "actions@github.com"
        
        # Add folder model_output (sekarang ada di root)
        git add model_output/*
        
        git commit -m "Auto-update model artifacts [skip ci]" || echo "No changes to commit"
        
        # Tarik perubahan terbaru dulu biar gak bentrok
        git pull --rebase origin main
        
        git push

    # 6. Login Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 7. Build & Push Docker Image
    - name: Build and Push Docker Image
      run: |
        # Ganti dengan username dockerhub kamu
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/submission-ml-wahyu:latest
        
        echo "Building Docker Image: $IMAGE_NAME"
        
        # Build docker dari folder model_output (langsung di root)
        mlflow models build-docker -m model_output -n $IMAGE_NAME --enable-mlserver
        
        # Push ke Docker Hub
        docker push $IMAGE_NAME