name: Kriteria 3 - CI Pipeline & Docker

on:
  push:
    paths:
      - 'kriteria3/**'  # Trigger hanya jika ada perubahan di folder kriteria3
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-train-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    # 3. Install Dependencies
    - name: Install dependencies
      run: |
        pip install mlflow pandas scikit-learn numpy matplotlib

    # 4. Run MLflow Project (Training)
    - name: Train Model
      run: |
        cd kriteria3
        python modelling.py

    # 5. Commit Artifacts (Model Output) ke GitHub Repo
    - name: Commit Model Artifacts
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "actions@github.com"
        
        # Add folder model_output yang ada di dalam kriteria3
        git add kriteria3/model_output/*
        
        git commit -m "Auto-update model artifacts [skip ci]" || echo "No changes to commit"
        
        # PENTING: Pull dulu biar sinkron dan gak error rejected
        git pull --rebase origin main
        
        git push

    # 6. Login Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 7. Build & Push Docker Image ke Docker Hub
    - name: Build and Push Docker Image
      run: |
        cd kriteria3
        
        # Ganti 'submission-ml-wahyu' kalau mau nama image lain
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/workflow-ci:latest
        
        echo "Building Docker Image: $IMAGE_NAME"
        
        # Build docker dari folder model_output
        # Option -m model_output artinya dia cari folder di dalam 'cd kriteria3' tadi
        mlflow models build-docker -m model_output -n $IMAGE_NAME --enable-mlserver
        
        # Push ke Docker Hub
        docker push $IMAGE_NAME